import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  margreteSidebar: [{ type: "autogenerated", dirName: "margrete" }],
  umiguriSidebar: [{ type: "autogenerated", dirName: "umiguri" }],
};

export default sidebars;
